import { readFileSync } from 'fs';

/** Reads the token blocks straight out of notionkit.css so the tables cannot drift. */
export function readTokens(cssPath = 'notionkit.css') {
  // Strip comments first: the file header explains the two-block structure and
  // mentions `:root {` in prose, which would otherwise be found first.
  const css = readFileSync(cssPath, 'utf-8').replace(/\/\*[\s\S]*?\*\//g, '');
  const block = (sel) => {
    const at = css.indexOf(sel + ' {');
    let depth = 0;
    for (let i = at; i < css.length; i++) {
      if (css[i] === '{') depth++;
      else if (css[i] === '}') { depth--; if (depth === 0) return css.slice(at, i); }
    }
    throw new Error('block not found: ' + sel);
  };
  const parse = (text) => {
    const out = {};
    for (const m of text.matchAll(/(--nk-[a-z0-9-]+)\s*:\s*([^;]+);/g)) out[m[1]] = m[2].trim();
    return out;
  };
  const light = parse(block(':root'));
  const dark = parse(block('[data-theme="dark"]'));
  return { light, dark };
}

export const TOKEN_MEANING = {
  '--nk-bg': { en: 'Page background', de: 'Seitenhintergrund' },
  '--nk-bg-sidebar': { en: 'Sidebar and settings nav', de: 'Sidebar und Settings-Navigation' },
  '--nk-bg-hover': { en: 'Hover wash — a darkening, never a hue change', de: 'Hover-Hauch – eine Verdunkelung, nie ein Farbwechsel' },
  '--nk-bg-active': { en: 'Active/selected row', de: 'Aktive/ausgewählte Zeile' },
  '--nk-bg-callout': { en: 'Callouts, badges, key caps, segmented track', de: 'Callouts, Badges, Tasten, Segment-Schiene' },
  '--nk-bg-code': { en: 'Code block background', de: 'Hintergrund von Code-Blöcken' },
  '--nk-bg-card': { en: 'Board cards and white buttons — separate from --nk-bg so dark mode can lift them', de: 'Board-Karten und weiße Buttons – getrennt von --nk-bg, damit Dark Mode sie abheben kann' },
  '--nk-bg-input': { en: 'The filled input surface: inputs, selects, textareas, the emoji search', de: 'Die gefüllte Eingabefläche: Inputs, Selects, Textareas, die Emoji-Suche' },
  '--nk-text': { en: 'Body text. Never pure black', de: 'Fließtext. Nie reines Schwarz' },
  '--nk-text-secondary': { en: 'Secondary text, table headers, descriptions', de: 'Sekundärtext, Tabellenköpfe, Beschreibungen' },
  '--nk-text-tertiary': { en: 'Meta, placeholders, section labels', de: 'Meta, Platzhalter, Abschnittslabels' },
  '--nk-text-sidebar': { en: 'Tree items, breadcrumbs, topbar buttons — one step darker than secondary, as in Notion', de: 'Baum-Einträge, Breadcrumbs, Topbar-Buttons – eine Stufe dunkler als sekundär, wie in Notion' },
  '--nk-border': { en: 'Hairline separators, table grid, input borders', de: 'Haarlinien-Trenner, Tabellengitter, Input-Rahmen' },
  '--nk-border-strong': { en: 'Input hover, scrollbar thumbs, dashed frames, checkboxes', de: 'Input-Hover, Scrollbar-Griffe, gestrichelte Rahmen, Checkboxen' },
  '--nk-accent': { en: 'The one brand colour. Everything accented is mixed from it', de: 'Die eine Markenfarbe. Alles Akzentuierte wird daraus gemischt' },
  '--nk-on-accent': { en: 'Text and marks on top of the accent or danger fill', de: 'Text und Marken auf Akzent- oder Danger-Füllung' },
  '--nk-danger': { en: 'Destructive actions, inline code, negative deltas', de: 'Destruktive Aktionen, Inline-Code, negative Deltas' },
  '--nk-tag-gray-bg': { en: 'Tag fill (gray)', de: 'Tag-Fläche (Grau)' },
  '--nk-tag-gray-text': { en: 'Tag text (gray), near-black on the fill', de: 'Tag-Text (Grau), fast schwarz auf der Fläche' },
  '--nk-tag-brown-bg': { en: 'Tag fill (brown)', de: 'Tag-Fläche (Braun)' },
  '--nk-tag-brown-text': { en: 'Tag text (brown), near-black on the fill', de: 'Tag-Text (Braun), fast schwarz auf der Fläche' },
  '--nk-tag-orange-bg': { en: 'Tag fill (orange)', de: 'Tag-Fläche (Orange)' },
  '--nk-tag-orange-text': { en: 'Tag text (orange), near-black on the fill', de: 'Tag-Text (Orange), fast schwarz auf der Fläche' },
  '--nk-tag-yellow-bg': { en: 'Tag fill (yellow)', de: 'Tag-Fläche (Gelb)' },
  '--nk-tag-yellow-text': { en: 'Tag text (yellow), near-black on the fill', de: 'Tag-Text (Gelb), fast schwarz auf der Fläche' },
  '--nk-tag-green-bg': { en: 'Tag fill (green)', de: 'Tag-Fläche (Grün)' },
  '--nk-tag-green-text': { en: 'Tag text (green), near-black on the fill', de: 'Tag-Text (Grün), fast schwarz auf der Fläche' },
  '--nk-tag-blue-bg': { en: 'Tag fill (blue)', de: 'Tag-Fläche (Blau)' },
  '--nk-tag-blue-text': { en: 'Tag text (blue), near-black on the fill', de: 'Tag-Text (Blau), fast schwarz auf der Fläche' },
  '--nk-tag-purple-bg': { en: 'Tag fill (purple)', de: 'Tag-Fläche (Lila)' },
  '--nk-tag-purple-text': { en: 'Tag text (purple), near-black on the fill', de: 'Tag-Text (Lila), fast schwarz auf der Fläche' },
  '--nk-tag-pink-bg': { en: 'Tag fill (pink)', de: 'Tag-Fläche (Pink)' },
  '--nk-tag-pink-text': { en: 'Tag text (pink), near-black on the fill', de: 'Tag-Text (Pink), fast schwarz auf der Fläche' },
  '--nk-tag-red-bg': { en: 'Tag fill (red)', de: 'Tag-Fläche (Rot)' },
  '--nk-tag-red-text': { en: 'Tag text (red), near-black on the fill', de: 'Tag-Text (Rot), fast schwarz auf der Fläche' },
  '--nk-tint-gray': { en: 'Soft gray surface for banners and tinted blocks', de: 'Weiche Grau-Fläche für Banner und getönte Blöcke' },
  '--nk-color-gray': { en: 'Coloured text and marks (gray)', de: 'Farbiger Text und Marken (Grau)' },
  '--nk-tint-brown': { en: 'Soft brown surface for banners and tinted blocks', de: 'Weiche Braun-Fläche für Banner und getönte Blöcke' },
  '--nk-color-brown': { en: 'Coloured text and marks (brown)', de: 'Farbiger Text und Marken (Braun)' },
  '--nk-tint-orange': { en: 'Soft orange surface for banners and tinted blocks', de: 'Weiche Orange-Fläche für Banner und getönte Blöcke' },
  '--nk-color-orange': { en: 'Coloured text and marks (orange) — also date mentions and code attributes', de: 'Farbiger Text und Marken (Orange) – zugleich Datums-Erwähnungen und Code-Attribute' },
  '--nk-tint-yellow': { en: 'Soft yellow surface for banners and tinted blocks', de: 'Weiche Gelb-Fläche für Banner und getönte Blöcke' },
  '--nk-color-yellow': { en: 'Coloured text and marks (yellow)', de: 'Farbiger Text und Marken (Gelb)' },
  '--nk-tint-green': { en: 'Soft green surface for banners and tinted blocks', de: 'Weiche Grün-Fläche für Banner und getönte Blöcke' },
  '--nk-color-green': { en: 'Coloured text and marks (green) — also the positive delta', de: 'Farbiger Text und Marken (Grün) – zugleich positives Delta' },
  '--nk-tint-blue': { en: 'Soft blue surface for banners and tinted blocks — also the progress track', de: 'Weiche Blau-Fläche für Banner und getönte Blöcke – zugleich Fortschritts-Schiene' },
  '--nk-color-blue': { en: 'Coloured text and marks (blue) — also the progress fill', de: 'Farbiger Text und Marken (Blau) – zugleich Fortschritts-Füllung' },
  '--nk-tint-purple': { en: 'Soft purple surface for banners and tinted blocks', de: 'Weiche Lila-Fläche für Banner und getönte Blöcke' },
  '--nk-color-purple': { en: 'Coloured text and marks (purple)', de: 'Farbiger Text und Marken (Lila)' },
  '--nk-tint-pink': { en: 'Soft pink surface for banners and tinted blocks', de: 'Weiche Pink-Fläche für Banner und getönte Blöcke' },
  '--nk-color-pink': { en: 'Coloured text and marks (pink)', de: 'Farbiger Text und Marken (Pink)' },
  '--nk-tint-red': { en: 'Soft red surface for banners and tinted blocks', de: 'Weiche Rot-Fläche für Banner und getönte Blöcke' },
  '--nk-color-red': { en: 'Coloured text and marks (red)', de: 'Farbiger Text und Marken (Rot)' },
  '--nk-decor-purple': { en: 'Avatar gradient start and cover. Same in both themes on purpose', de: 'Avatar-Verlauf-Start und Cover. Bewusst in beiden Themes gleich' },
  '--nk-decor-blue': { en: 'Avatar gradient end and cover', de: 'Avatar-Verlauf-Ende und Cover' },
  '--nk-decor-orange': { en: 'Cover accent', de: 'Cover-Akzent' },
  '--nk-scrim': { en: 'Modal backdrop', de: 'Modal-Backdrop' },
  '--nk-scrim-soft': { en: 'Command palette backdrop, one step lighter', de: 'Backdrop der Befehlspalette, eine Stufe heller' },
  '--nk-sidebar-width': { en: 'Sidebar width, also its min-width (plus the left safe-area inset, if any)', de: 'Sidebar-Breite, zugleich ihre min-width (plus linker Safe-Area-Inset, falls vorhanden)' },
  '--nk-tab-bar-height': { en: 'Mobile tab bar height without the safe-area inset (the inset replaces the 6px bottom padding); the spacer uses the same value', de: 'Höhe der mobilen Tab-Bar ohne Safe-Area; der Platzhalter nutzt denselben Wert' },
  '--nk-radius': { en: 'Control radius. Cards and modals use 8–12px directly', de: 'Radius für Bedienelemente. Karten und Modals nutzen direkt 8–12px' },
  '--nk-font': { en: 'System font stack', de: 'System-Schriftstapel' },
  '--nk-font-mono': { en: 'Monospace stack for code', de: 'Monospace-Stapel für Code' },
  '--nk-shadow-menu': { en: 'Three-layer shadow for every floating surface', de: 'Dreilagiger Schatten für jede schwebende Fläche' },
  '--nk-shadow-card': { en: 'Board card lift. `none` in dark mode', de: 'Abheben der Board-Karte. Im Dark Mode `none`' },
  '--nk-shadow-btn': { en: 'The white button’s outline: a 1px inset ring plus a 1px drop, no border', de: 'Die Kontur des weißen Buttons: 1px-Innenring plus 1px Schatten, kein Rahmen' },
  '--nk-shadow-knob': { en: 'Switch knob', de: 'Switch-Knopf' },
  '--nk-shadow-segment': { en: 'Active segment', de: 'Aktives Segment' },
  'color-scheme': { en: 'Tells the browser which scheme its own widgets should use', de: 'Sagt dem Browser, welches Schema seine eigenen Widgets nutzen sollen' },
};

export const STATES = [
  { cls: '[hidden]', on: '[class*="nk-"], ::slotted(*)',
    en: 'Hides, always – also on components that set their own display, which beat the browser rule before 1.5.2. hidden="until-found" keeps the browser’s find-in-page reveal.',
    de: 'Blendet aus, immer – auch Komponenten mit eigenem display, die vor 1.5.2 die Browser-Regel schlugen. hidden="until-found" behält das Aufdecken per Seitensuche des Browsers.' },
  { cls: 'active', on: 'nk-tree-item, nk-db-tab, nk-tab, nk-tab-bar-item, nk-settings-pane, nk-segmented button, nk-emoji-cats span, nk-board, nk-bubble-menu button',
    en: 'Marks the current item. Tree items and view tabs get the active background, .nk-tab gets the underline, panes become visible.',
    de: 'Markiert das aktuelle Element. Baum-Einträge und View-Reiter bekommen den Aktiv-Hintergrund, .nk-tab die Unterlinie, Panes werden sichtbar.' },
  { cls: 'open', on: 'nk-modal-backdrop, nk-cmdk-backdrop, nk-sheet-backdrop, nk-dialog-backdrop, nk-peek-backdrop, nk-pop.floating, nk-tooltip, nk-sidebar, nk-sidebar-backdrop, nk-toggle-arrow',
    en: 'Fades the overlay in and makes it interactive; slides the side peek in from the right; shows a floating menu or a tooltip; slides the sidebar in as a drawer on a phone; rotates the toggle arrow by 90°.',
    de: 'Blendet das Overlay ein und macht es bedienbar; schiebt den Side Peek von rechts herein; zeigt ein schwebendes Menü oder einen Tooltip; schiebt die Sidebar auf dem Telefon als Schublade herein; dreht den Toggle-Pfeil um 90°.' },
  { cls: 'peek-inset', on: 'nk-app',
    en: 'While the side peek is open: the main column gets a right padding as wide as the peek, so the page moves aside instead of lying under it. Desktop only.',
    de: 'Solange der Side Peek offen ist: Die Hauptspalte bekommt rechts ein Padding so breit wie der Peek, die Seite rückt also zur Seite, statt darunter zu liegen. Nur auf dem Desktop.' },
  { cls: 'copied', on: 'nk-copy-field .cf-btn',
    en: 'The moment after copying: the action turns green. Set it after the clipboard write and take it off again.',
    de: 'Der Moment nach dem Kopieren: Die Aktion wird grün. Nach dem Schreiben in die Zwischenablage setzen und wieder abnehmen.' },
  { cls: 'square', on: 'nk-profile-row .big-avatar',
    en: 'The rounded square of a workspace icon instead of the circle of a person.',
    de: 'Das abgerundete Quadrat eines Workspace-Icons statt des Kreises einer Person.' },
  { cls: 'floating', on: 'nk-pop',
    en: 'A menu over the page: invisible and inert until .open, then it fades in and settles from 4px higher and 98 %, the way the palette opens.',
    de: 'Ein Menü über der Seite: unsichtbar und inaktiv bis .open, dann blendet es ein und setzt sich aus 4px Höhe und 98 % ab, so wie die Palette öffnet.' },
  { cls: 'sheet', on: 'nk-pop',
    en: 'Below 860px the popover becomes a bottom sheet – full width, grabber, 40px rows, the page dimmed – and inline positioning is overruled.',
    de: 'Unter 860px wird das Popover zum Bottom Sheet – volle Breite, Griff, 40px-Zeilen, die Seite abgedunkelt –, eine Inline-Position wird übergangen.' },
  { cls: 'done / current', on: 'nk-step',
    en: 'A finished step on the green tag with a check; the step you are on, ringed in the accent, with aria-current="step".',
    de: 'Ein erledigter Schritt auf dem grünen Tag mit Haken; der Schritt, auf dem man steht, im Akzent umrandet, mit aria-current="step".' },
  { cls: 'collapsed', on: 'nk-tree-children, nk-sidebar, nk-sidebar-toggle',
    en: 'Folds a subtree away with display: none. On the sidebar it slides it out to the left on the desktop; on the ☰ it shows the button that brings it back.',
    de: 'Klappt einen Unterbaum per display: none weg. An der Sidebar schiebt es sie auf dem Desktop nach links hinaus; am ☰ zeigt es den Button, der sie zurückholt.' },
  { cls: 'selected', on: 'nk-cmdk-item, nk-model-card, nk-slash-item, nk-calendar .cal-day',
    en: 'The keyboard-highlighted or chosen option – on a calendar the chosen day, in the accent. Distinct from active: selection is transient, active is where you are.',
    de: 'Die per Tastatur hervorgehobene oder gewählte Option – im Kalender der gewählte Tag, im Akzent. Anders als active: Auswahl ist flüchtig, active ist der Ort, an dem du bist.' },
  { cls: 'start / end / in-range', on: 'nk-calendar .cal-day',
    en: 'A range: its first and last day in the accent, rounded on the outer side, the days between in the accent’s tint. A range of one day is start and end.',
    de: 'Ein Zeitraum: erster und letzter Tag im Akzent, außen gerundet, die Tage dazwischen in der Tönung des Akzents. Ein Zeitraum von einem Tag ist start und end.' },
  { cls: 'today / off / out', on: 'nk-calendar .cal-day, nk-calendar-view .cv-day',
    en: 'Today in red – on the calendar view a red pill; a day not worked (weekend, holiday) greyed or washed; a day of the month before or after, the same.',
    de: 'Heute in Rot – in der Kalenderansicht eine rote Pille; ein Tag ohne Arbeit (Wochenende, Feiertag) gegraut bzw. hinterlegt; ein Tag des Monats davor oder danach ebenso.' },
  { cls: 'weeks', on: 'nk-calendar, nk-calendar-view',
    en: 'Adds the column of ISO calendar weeks in front of the days.',
    de: 'Ergänzt die Spalte der ISO-Kalenderwochen vor den Tagen.' },
  { cls: 'stacked', on: 'nk-field',
    en: 'Label above a full-width control instead of beside it – textareas, long descriptions.',
    de: 'Label über einem vollbreiten Control statt daneben – Textareas, lange Beschreibungen.' },
  { cls: 'compact', on: 'nk-field, nk-tree-item, nk-select',
    en: 'The tighter variant: a field with a small tertiary label and no row padding (inside .nk-fields), a 26px tree row, a 120px select.',
    de: 'Die engere Variante: ein Feld mit kleinem tertiärem Label ohne Zeilen-Padding (in .nk-fields), eine 26px-Baumzeile, ein 120px-Select.' },
  { cls: 'scroll', on: 'nk-segmented',
    en: 'Scrolls the segments horizontally with the scrollbar hidden, capped at the parent width.',
    de: 'Scrollt die Segmente horizontal mit versteckter Scrollleiste, begrenzt auf die Elternbreite.' },
  { cls: 'wrap', on: 'nk-segmented, nk-table, nk-table td',
    en: 'Lets the segments wrap onto further rows; on a table or a cell, lets cell text break instead of staying on one line.',
    de: 'Lässt die Segmente in weitere Zeilen umbrechen; auf einer Tabelle oder Zelle lässt es Zellentext umbrechen statt einzeilig zu bleiben.' },
  { cls: 'fixed', on: 'nk-tab-bar',
    en: 'Pins the tab bar to the viewport bottom; a following .nk-tab-bar-spacer keeps its height in the flow.',
    de: 'Heftet die Tab-Bar an den unteren Viewport-Rand; ein folgender .nk-tab-bar-spacer hält ihre Höhe im Fluss frei.' },
  { cls: 'covered', on: 'nk-page',
    en: 'The page follows a cover: no top padding, the icon overlaps the cover’s bottom edge. Class markup gets this from .nk-cover + .nk-page; <nk-page cover> sets the class.',
    de: 'Die Seite folgt einem Cover: kein oberes Padding, das Icon überlappt die Cover-Unterkante. Klassen-Markup bekommt das über .nk-cover + .nk-page; <nk-page cover> setzt die Klasse.' },
  { cls: 'full', on: 'nk-page',
    en: 'Page option “Full width”: lifts the 760px cap, the column fills the window. Per page, as in Notion’s ⋯ menu.',
    de: 'Seitenoption „Volle Breite“: hebt die 760px-Grenze auf, die Spalte füllt das Fenster. Pro Seite, wie in Notions ⋯-Menü.' },
  { cls: 'small', on: 'nk-page, nk-avatar, nk-btn',
    en: 'Page option “Small text”: document text 14px instead of 16px; heading, lead, prose and editor follow. On an avatar 20px, on a button 24px.',
    de: 'Seitenoption „Kleiner Text“: Dokumenttext 14px statt 16px; Überschrift, Lead, Prosa und Editor ziehen mit. An einem Avatar 20px, an einem Button 24px.' },
  { cls: 'wide', on: 'nk-progress, nk-input, nk-select, nk-textarea',
    en: 'Fills its row. A wide progress bar grows from 60px in a flex row, so its label stays beside it.',
    de: 'Füllt seine Zeile. Ein breiter Fortschrittsbalken wächst in einer flex-Zeile ab 60px, sein Label bleibt also daneben.' },
  { cls: 'bubble', on: 'nk-ai-msg',
    en: 'The message as a grey bubble without avatar or name; with .user it sits on the right, as your own question does in Notion’s AI chat.',
    de: 'Die Nachricht als graue Blase ohne Avatar und Namen; mit .user steht sie rechts, wie die eigene Frage in Notions KI-Chat.' },
  { cls: 'last', on: 'nk-list-item, nk-member-row',
    en: 'Drops the row’s bottom line where the list cannot see the last child – a row rendered in its own shadow root.',
    de: 'Nimmt der Zeile die untere Linie, wo die Liste das letzte Kind nicht sieht – eine Zeile, die in ihrem eigenen Shadow Root steht.' },
  { cls: 'always', on: 'nk-tab-bar',
    en: 'Shows the tab bar at every width, not only below 860px – for previews and phone frames.',
    de: 'Zeigt die Tab-Bar in jeder Breite, nicht nur unter 860px – für Vorschauen und Telefon-Rahmen.' },
  { cls: 'show', on: 'nk-toast',
    en: 'Slides the toast up from below and fades it in.', de: 'Fährt den Toast von unten hoch und blendet ihn ein.' },
  { cls: 'aria-checked="true"', on: 'nk-switch (button form)',
    en: 'Fills the track with the accent and slides the knob. An attribute, not a class, so the state is also announced to assistive technology.',
    de: 'Füllt die Schiene mit dem Akzent und schiebt den Knopf. Ein Attribut, keine Klasse – der Zustand wird so auch an assistive Technik gemeldet.' },
  { cls: ':checked', on: 'nk-todo input, nk-check input, nk-switch (input form)',
    en: 'Native state. Draws the custom checkmark or dot and strikes a to-do label through.',
    de: 'Nativer Zustand. Zeichnet Haken oder Punkt und streicht ein To-do-Label durch.' },
  { cls: 'nk-drop-target', on: 'nk-block-host',
    en: 'Drag feedback: a 2px accent line above the block.', de: 'Drag-Rückmeldung: eine 2px-Akzentlinie über dem Block.' },
];

// Measured with the sRGB relative-luminance formula against the surface the
// pair actually sits on. See tools/contrast.mjs.
export const CONTRAST = [
  { pair: '--nk-text / --nk-bg', light: 13.98, dark: 11.78, body: true },
  { pair: '--nk-text / --nk-bg-sidebar', light: 13.18, dark: 11.06, body: true },
  { pair: '--nk-text-sidebar / --nk-bg-sidebar', light: 6.11, dark: 7.03, body: true },
  { pair: '--nk-text-secondary / --nk-bg', light: 4.27, dark: 4.63, body: true },
  { pair: '--nk-text-tertiary / --nk-bg', light: 3.16, dark: 2.91, body: false },
  { pair: '--nk-accent / --nk-bg', light: 3.88, dark: 5.83, body: false },
  { pair: '--nk-on-accent / --nk-accent', light: 3.88, dark: 3.01, body: true },
  { pair: '--nk-danger / --nk-bg', light: 4.88, dark: 4.63, body: true },
  { pair: 'tag gray', light: 10.17, dark: 9.10, body: false },
  { pair: 'tag blue', light: 10.12, dark: 7.56, body: false },
  { pair: 'tag green', light: 10.41, dark: 6.37, body: false },
  { pair: 'tag orange', light: 10.18, dark: 5.49, body: false },
  { pair: 'tag yellow', light: 11.30, dark: 4.42, body: false },
  { pair: 'tag purple', light: 10.04, dark: 8.59, body: false },
  { pair: 'tag red', light: 10.74, dark: 7.30, body: false },
];
