// Phrases used inside the component previews. One dictionary per language so
// the catalog itself stays language-neutral.
export const WORDS = {
  en: {
    workspace: 'Acme Inc', search: 'Search', home: 'Home', inbox: 'Inbox',
    favourites: 'Favourites', pages: 'Pages', share: 'Share', settings: 'Settings',
    projectOverview: 'Project overview', knowledgeBase: 'Knowledge base',
    designSystem: 'Design system', roadmap: 'Roadmap', meetingNotes: 'Meeting notes',
    pageTitle: 'Product roadmap', lastEdited: 'Last edited 2 min ago',
    created: 'Created 12 May 2026', author: 'Ada Lovelace',
    lead: 'A short lead paragraph sets up the page in a calmer, larger type size before the body copy begins.',
    heading: 'How this works',
    calloutBody: '<b>Core idea:</b> a callout carries one thought that should not be missed. Keep it to a sentence or two.',
    todo1: 'Sketch the component scope', todo2: 'Build the preview', todo3: 'Prioritise the MVP',
    toggleSummary: 'What is not included?', toggleBody: 'The text editor itself. NotionKit ships the optical shell; you mount TipTap, BlockNote or Novel inside it.',
    quote: 'Design is not just what it looks like. Design is how it works.', quoteCite: '— Steve Jobs',
    mentionPerson: 'Sara Lindt', mentionDate: '20 May',
    name: 'Name', status: 'Status', owner: 'Owner', due: 'Due', progress: 'Progress',
    newPage: '＋ New page', table: 'Table', board: 'Board', gallery: 'Gallery',
    planned: 'Planned', inProgress: 'In progress', done: 'Done',
    tableView: 'Table view', boardView: 'Board view', emojiPicker: 'Emoji picker',
    displayName: 'Display name', displayNameDesc: 'How you appear in the workspace.',
    email: 'Email', aboutMe: 'About me', placeholderName: 'Ada Lovelace',
    placeholderAbout: 'A few words about yourself …',
    save: 'Save changes', discard: 'Discard', deleteIt: 'Delete', remove: 'Remove',
    compactView: 'Compact view', compactDesc: 'Reduces spacing in the sidebar and lists.',
    reduceMotion: 'Reduce motion', textSize: 'Text size',
    option1: 'Light', option2: 'Dark', option3: 'System',
    modelName: 'Mona Standard', modelRecommended: 'Recommended',
    modelDesc: 'A balanced model for everyday work. Fast, calm, dependable.',
    dangerTitle: '⚠️ Danger zone', dangerText: 'Irreversibly removes all pages, databases and members.',
    memberRole: 'Member', memberAdmin: 'Admin',
    rename: 'Rename', duplicate: 'Duplicate', copyLink: 'Copy link', moveToTrash: 'Move to trash',
    actions: 'Actions', cmdkPlaceholder: 'Search or type a command …',
    openSettings: 'Open settings', newPageCmd: 'New page', navigate: 'navigate', open: 'open', toggle: 'toggle',
    toastMsg: 'Settings saved', noResults: 'No results for',
    notes: 'Notes', tasks: 'Tasks', files: 'Files',
    tabPanelBody: 'Panel content follows the tab strip and inherits the calm body type.',
    insertWeek: '📅 Insert week plan', insertMinutes: '🤝 Insert meeting minutes',
    activePages: 'Active pages', aiRequests: 'AI requests', openTasks: 'Open tasks',
    thisWeek: 'this week', sinceYesterday: 'since yesterday',
    syncedBadge: '⟳ 3 places', syncedBody: 'This text appears identically on three pages and is maintained in one place.',
    week: 'Week', month: 'Month', quarter: 'Quarter',
    bannerInfo: 'The “Project overview” database has 2 overdue entries.', bannerAction: 'View',
    bannerSuccess: 'All changes have been synced.', bannerWarning: 'Your trial ends in 5 days.',
    peopleAccess: '5 people have access',
    emptyTitle: 'No entries yet', emptyDesc: 'Create the first entry or import existing data.',
    emptyBtn: '＋ New entry',
    commentAuthor: 'Sara Lindt', commentWhen: '· 1 hr ago',
    commentBody: 'The board view already feels very close to the original. 👍',
    commentPlaceholder: 'Comment …', send: 'Send',
    you: 'You', ai: 'Mona', aiSuffix: '· AI',
    aiUser: 'Summarise the open tasks for this project.',
    aiReply: 'Two tasks are open: the table view sits at 65 %, the board with drag and drop is planned.',
    aiCopy: '📋 Copy', aiRephrase: '↻ Rephrase', aiPlaceholder: 'Ask Mona something …',
    editorPlaceholder: 'Type “/” for commands …',
    slashHeading: 'Heading 1', slashHeadingDesc: 'Big section heading',
    slashTodo: 'To-do list', slashTodoDesc: 'Track tasks with a checkbox',
    slashCode: 'Code block', slashCodeDesc: 'Capture a snippet',
    slashBasic: 'Basic blocks',
  },
  de: {
    workspace: 'Acme GmbH', search: 'Suche', home: 'Start', inbox: 'Posteingang',
    favourites: 'Favoriten', pages: 'Seiten', share: 'Teilen', settings: 'Einstellungen',
    projectOverview: 'Projektübersicht', knowledgeBase: 'Wissensdatenbank',
    designSystem: 'Design-System', roadmap: 'Roadmap', meetingNotes: 'Meeting-Notizen',
    pageTitle: 'Produkt-Roadmap', lastEdited: 'Zuletzt bearbeitet: vor 2 Min.',
    created: 'Erstellt am 12. Mai 2026', author: 'Ada Lovelace',
    lead: 'Ein kurzer Lead-Absatz führt in die Seite ein – ruhiger und etwas größer gesetzt als der Fließtext, der darunter beginnt.',
    heading: 'So funktioniert das',
    calloutBody: '<b>Leitidee:</b> Ein Callout trägt genau einen Gedanken, der nicht übersehen werden darf. Ein bis zwei Sätze reichen.',
    todo1: 'Komponenten-Umfang skizzieren', todo2: 'Preview bauen', todo3: 'MVP-Umfang priorisieren',
    toggleSummary: 'Was ist nicht enthalten?', toggleBody: 'Der Text-Editor selbst. NotionKit liefert die optische Hülle; TipTap, BlockNote oder Novel hängst du hinein.',
    quote: 'Design ist nicht, wie etwas aussieht. Design ist, wie es funktioniert.', quoteCite: '— Steve Jobs',
    mentionPerson: 'Sara Lindt', mentionDate: '20. Mai',
    name: 'Name', status: 'Status', owner: 'Verantwortlich', due: 'Fällig', progress: 'Fortschritt',
    newPage: '＋ Neue Seite', table: 'Tabelle', board: 'Board', gallery: 'Galerie',
    planned: 'Geplant', inProgress: 'In Arbeit', done: 'Fertig',
    tableView: 'Tabellen-Ansicht', boardView: 'Board-Ansicht', emojiPicker: 'Emoji-Picker',
    displayName: 'Anzeigename', displayNameDesc: 'So wirst du im Workspace angezeigt.',
    email: 'E-Mail', aboutMe: 'Über mich', placeholderName: 'Ada Lovelace',
    placeholderAbout: 'Ein paar Worte über dich …',
    save: 'Änderungen speichern', discard: 'Verwerfen', deleteIt: 'Löschen', remove: 'Entfernen',
    compactView: 'Kompakte Ansicht', compactDesc: 'Reduziert Abstände in Sidebar und Listen.',
    reduceMotion: 'Animationen reduzieren', textSize: 'Textgröße',
    option1: 'Hell', option2: 'Dunkel', option3: 'System',
    modelName: 'Mona Standard', modelRecommended: 'Empfohlen',
    modelDesc: 'Ausgewogenes Modell für den Arbeitsalltag. Schnell, ruhig, zuverlässig.',
    dangerTitle: '⚠️ Gefahrenbereich', dangerText: 'Entfernt alle Seiten, Datenbanken und Mitglieder unwiderruflich.',
    memberRole: 'Mitglied', memberAdmin: 'Admin',
    rename: 'Umbenennen', duplicate: 'Duplizieren', copyLink: 'Link kopieren', moveToTrash: 'In den Papierkorb',
    actions: 'Aktionen', cmdkPlaceholder: 'Suchen oder Befehl eingeben …',
    openSettings: 'Einstellungen öffnen', newPageCmd: 'Neue Seite', navigate: 'navigieren', open: 'öffnen', toggle: 'umschalten',
    toastMsg: 'Einstellungen gespeichert', noResults: 'Keine Ergebnisse für',
    notes: 'Notizen', tasks: 'Aufgaben', files: 'Dateien',
    tabPanelBody: 'Der Panel-Inhalt folgt der Reiterleiste und erbt die ruhige Fließtext-Typografie.',
    insertWeek: '📅 Wochenplan einfügen', insertMinutes: '🤝 Meeting-Protokoll einfügen',
    activePages: 'Aktive Seiten', aiRequests: 'KI-Anfragen', openTasks: 'Offene Aufgaben',
    thisWeek: 'diese Woche', sinceYesterday: 'seit gestern',
    syncedBadge: '⟳ 3 Orte', syncedBody: 'Dieser Text erscheint identisch auf drei Seiten und wird zentral gepflegt.',
    week: 'Woche', month: 'Monat', quarter: 'Quartal',
    bannerInfo: 'Die Datenbank „Projektübersicht“ hat 2 überfällige Einträge.', bannerAction: 'Ansehen',
    bannerSuccess: 'Alle Änderungen wurden synchronisiert.', bannerWarning: 'Deine Testphase endet in 5 Tagen.',
    peopleAccess: '5 Personen haben Zugriff',
    emptyTitle: 'Noch keine Einträge', emptyDesc: 'Lege den ersten Eintrag an oder importiere vorhandene Daten.',
    emptyBtn: '＋ Neuer Eintrag',
    commentAuthor: 'Sara Lindt', commentWhen: '· vor 1 Std.',
    commentBody: 'Die Board-Ansicht fühlt sich schon sehr nah am Original an. 👍',
    commentPlaceholder: 'Kommentieren …', send: 'Senden',
    you: 'Du', ai: 'Mona', aiSuffix: '· KI',
    aiUser: 'Fasse die offenen Aufgaben dieses Projekts zusammen.',
    aiReply: 'Zwei Aufgaben sind offen: Die Tabellen-Ansicht steht bei 65 %, das Board mit Drag-and-Drop ist geplant.',
    aiCopy: '📋 Kopieren', aiRephrase: '↻ Neu formulieren', aiPlaceholder: 'Mona etwas fragen …',
    editorPlaceholder: 'Tippe „/“ für Befehle …',
    slashHeading: 'Überschrift 1', slashHeadingDesc: 'Große Abschnitts-Überschrift',
    slashTodo: 'To-do-Liste', slashTodoDesc: 'Aufgaben mit Checkbox verfolgen',
    slashCode: 'Code-Block', slashCodeDesc: 'Ein Snippet festhalten',
    slashBasic: 'Basis-Blöcke',
  },
};
